16:06:55.237 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Authentication Failure', status=401, detail='Bad credentials', instance='null', properties='null']
16:33:13.338 [http-nio-8080-exec-3] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Authentication Failure', status=401, detail='Bad credentials', instance='null', properties='null']
17:25:31.572 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
17:31:14.930 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
17:36:19.694 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
17:50:17.152 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:08:45.211 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:11:10.625 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:11:40.958 [http-nio-8080-exec-2] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:17:12.197 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:18:37.232 [http-nio-8080-exec-3] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:21:00.759 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:38:40.991 [http-nio-8080-exec-5] ERROR c.d.b.e.h.GlobalExceptionHandler - ProblemDetail[type='about:blank', title='Duplicate name not allowed', status=409, detail='community with name: string already exist', instance='null', properties='null']
18:39:39.138 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:40:13.566 [http-nio-8080-exec-3] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
18:42:41.301 [http-nio-8080-exec-1] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
23:58:09.550 [http-nio-8080-exec-8] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Jwt Error', status=401, detail='Invalid JWT signature: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.', instance='null', properties='null']
00:47:31.840 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Email Already Exists', status=409, detail='User with email: email already exists already exists!', instance='null', properties='null']
00:47:32.400 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Authentication Failure', status=401, detail='not authenticated ', instance='null', properties='null']
00:47:32.510 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='User Already Exists', status=409, detail='User with username: user already exists already exists!', instance='null', properties='null']
00:48:32.319 [main] ERROR c.d.b.e.h.GlobalExceptionHandler - ProblemDetail[type='about:blank', title='Not Found', status=404, detail='User not found', instance='null', properties='null']
00:59:06.594 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Email Already Exists', status=409, detail='User with email: email already exists already exists!', instance='null', properties='null']
00:59:06.926 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='Authentication Failure', status=401, detail='not authenticated ', instance='null', properties='null']
00:59:06.992 [main] ERROR c.d.b.e.h.AuthenticationExceptionHandler - ProblemDetail[type='about:blank', title='User Already Exists', status=409, detail='User with username: user already exists already exists!', instance='null', properties='null']
00:59:44.754 [main] ERROR c.d.b.e.h.GlobalExceptionHandler - ProblemDetail[type='about:blank', title='Not Found', status=404, detail='User not found', instance='null', properties='null']
